# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: cicdvm
#  vmImage: windows-latest

variables: 
  system.debug: 'true'

steps:

- task: PowerBIActions@5
  inputs:
    Action: 'Workspace'
    WorkspaceName: 'testing_ws'
    Name: 'myname'

- task: PowerBIActions@5
  inputs:
    Action: 'AddGroup'
    WorkspaceName: 'testing_ws'
    GroupObjectIds: '5f543377-1b5c-4bf0-9760-6413d8466c70'
    Permission: 'Admin'
    
- task: PowerBIActions@5
  inputs:
    PowerBIServiceEndpoint: 'PBI Service Connection'
    Action: 'Publish'
    WorkspaceName: 'workingtest_ws'
    PowerBIPath: '**/sqlserversourcedata.pbix'