# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: cicdvm
#  vmImage: windows-latest

variables: 
  system.debug: 'true'

steps:
- task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
  displayName: 'Power BI Action: Create Workspace'
  inputs:
    PowerBIServiceEndpoint: 'PBI Service Connection'
    Action: Workspace
    WorkspaceName: baselinews

- task: PowerBIActions@5
  inputs:
    Action: 'AddUsers'
    WorkspaceName: 'baselinews'
    Create: true
    Users: 'gdardia@all2me.cloud'
    Permission: 'Admin'

- task: PowerBIActions@5
  inputs:
    Action: 'AddSP'
    WorkspaceName: 'baselinews'
    Create: false
    ServicePrincipals: '9043ed8f-e4b7-4484-afd3-69194d8095e1'
    Permission: 'Admin'